---

nsxv_edge_params: &nsxv-edge-params
  VCENTER_HOST: {{vcenter_host}}
  VCENTER_USR: {{vcenter_usr}}
  VCENTER_PWD: {{vcenter_pwd}}
  VCENTER_DATA_CENTER: {{vcenter_data_center}}
  VCENTER_CLUSTER: {{vcenter_cluster}}
  NSX_EDGE_GEN_NAME: {{nsx_edge_gen_name}}
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS: {{nsx_edge_gen_nsx_manager_address}}
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER: {{nsx_edge_gen_nsx_manager_admin_user}}
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD: {{nsx_edge_gen_nsx_manager_admin_passwd}}
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE: {{nsx_edge_gen_nsx_manager_transport_zone}}
  NSX_EDGE_GEN_EDGE_DATASTORE: {{nsx_edge_gen_edge_datastore}}
  NSX_EDGE_GEN_EDGE_CLUSTER: {{nsx_edge_gen_edge_cluster}}

resources:
- name: haas-1.5-nsxv
  type: git
  source:
    uri: https://github.com/lamlouis/pez-haas-1.5

jobs:
- name: destroy-edge
  plan:
  - aggregate:
    - get: haas-1.5-nsxv
  - task: destroy-edge
    file: haas-1.5-nsxv/tasks/vsphere/nsxv/destroy-edge/task.yml
    params: *nsxv-edge-params

- name: create-edge
  plan:
  - aggregate:
    - get: haas-1.5-nsxv
  - task: create-edge
    file: haas-1.5-nsxv/tasks/vsphere/nsxv/create-edge/task.yml
    params: *nsxv-edge-params
