---

nsxv_edge_params: &nsxv-edge-params
  HAAS_SLOT: {{haas_slot}}
  HAAS_SLOT_NETWORKS: {{haas_slot_networks}}
  VCENTER_HOST: {{vcenter_host}}
  VCENTER_USR: {{vcenter_usr}}
  VCENTER_PWD: {{vcenter_pwd}}
  VCENTER_DATA_CENTER: {{vcenter_data_center}}
  VCENTER_CLUSTER: {{vcenter_cluster}}
  ESX_USR: {{esx_usr}}
  ESX_PWD: {{esx_pwd}}
  ESX_HOST: {{esx_host}}
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS: {{nsx_edge_gen_nsx_manager_address}}
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER: {{nsx_edge_gen_nsx_manager_admin_user}}
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD: {{nsx_edge_gen_nsx_manager_admin_passwd}}
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE: {{nsx_edge_gen_nsx_manager_transport_zone}}
  NSX_EDGE_GEN_EDGE_DATASTORE: {{nsx_edge_gen_edge_datastore}}
  NSX_EDGE_GEN_EDGE_CLUSTER: {{nsx_edge_gen_edge_cluster}}
  NSX_EDGE_GEN_NAME: {{nsx_edge_gen_name}}
  ESG_CLI_PASSWORD_1: {{esg_cli_password_1}}
  ERT_SSL_CERT: {{ert_ssl_cert}}
  ERT_SSL_PRIVATE_KEY: {{ert_ssl_private_key}}
  ESG_UPLINK_PG: {{esg_uplink_pg}}
  ESG_UPLINK_IP: {{esg_uplink_ip}}
  ESG_UPLINK_MASK: {{esg_uplink_mask}}
  ESG_INTERNAL_PG_1: {{esg_internal_pg_1}}
  ESG_INTERNAL_IP_1: {{esg_internal_ip_1}}
  ESG_INTERNAL_LB_IP_1: {{esg_internal_lb_ip_1}}
  ESG_INTERNAL_MASK_1: {{esg_internal_mask_1}}
  ESG_INTERNAL_PG_2: {{esg_internal_pg_2}}
  ESG_INTERNAL_IP_2: {{esg_internal_ip_2}}
  ESG_INTERNAL_MASK_2: {{esg_internal_mask_2}}
  ESG_OSPF_AREA: {{esg_ospf_area}}
  ESG_OSPF_PASSWORD: {{esg_ospf_password}}
  ESG_DEFAULT_GATEWAY: {{esg_default_gateway}}
  T0_ROUTER_IP: {{t0_router_ip}}
  T0_STATIC_ROUTES: {{t0_static_routes}}
  OM_NAT_IP: {{om_nat_ip}}
  ERT_NAT_IP: {{ert_nat_ip}}
  PKS_NAT_IP: {{pks_nat_ip}}
  SECOND_VLAN: {{second_vlan}}
  MTU: {{mtu}}


resources:
- name: haas-1.5-nsxv
  type: git
  source:
    uri: https://github.com/lamlouis/pez-haas-1.5

jobs:

- name: get-started-job
  max_in_flight: 1
  plan:
  - get: haas-1.5-nsxv
  - task: get-started-task
    file: haas-1.5-nsxv/tasks/vsphere/nsxv/destroy-edge/task.yml
    params: *nsxv-edge-params



- name: destroy-edge
  max_in_flight: 1
  plan:
    - get: haas-1.5-nsxv
      passed: [get-started-job]
      trigger: true
  - task: destroy-edge
    file: haas-1.5-nsxv/tasks/vsphere/nsxv/destroy-edge/task.yml
    params: *nsxv-edge-params

- name: create-edge
  max_in_flight: 1
  plan:
    - get: haas-1.5-nsxv
      passed: [destroy-edge]
      trigger: true
  - task: create-edge
    file: haas-1.5-nsxv/tasks/vsphere/nsxv/create-edge/task.yml
    params: *nsxv-edge-params

- name: vmware-config
  max_in_flight: 1
  plan:
    - get: haas-1.5-nsxv
      passed: [get-started-job]
      trigger: true
  - task: vmware-config
    file: haas-1.5-nsxv/tasks/vsphere/vmware-config/task.yml
    params: *nsxv-edge-params
